Add regression testing.
Creat a target. The target includes a file which is essentially a script.
Add kernel building to the standard mkfile, so we always build
kernels as part of jenkinshook.

The jenkinshook file is designed to be run from a script outside
this directory, but that script is simple, e.g.
export JENKINSHOOK=/home/rminnich
bash jenkinshook

Also it would be best if we could build a
disk image with grub and boot that in qemu.

The next step is to modify my jenkinshook sript to run
this jenkinshook; then the jenkins hook and regression
testing will be contained entirely in the NxM tree.

Change-Id: I4acaa3d7d4b2c856b841f89e9de86e7a2ef2a213
Signed-off-by: Ronald G. Minnich <rminnich@gmail.com>
Reviewed-on: http://nxm.coreboot.org/review/217
Tested-by: Jenkins QA
Reviewed-by: John Floren <john@jfloren.net>

diff --git a/jenkinshook b/jenkinshook
--- a/jenkinshook
+++ b/jenkinshook
@@ -1,17 +1,33 @@
 #!/bin/bash
+# This script assumes you have set JENKINSHOME
+# in the environment. If you have not it will fail, which
+# will be quickly caught by jenkins, so there's no checking.
+. $JENKINSHOME/.bashrc
 echo "WARNING:This will fail if $NXM/xbin is in your PATH"
 set -e
 go version
 9c --version
-cp inferno-os/mkconfig.jenkins inferno-os/mkconfig
+cp /$JENKINSHOME/mkconfig.jenkins inferno-os/mkconfig
 sh BUILDTOOLCHAIN
-. SETUP
+# `special` system like suse want . files fully qualified
+. ./SETUP
 cd sys/src
 mk nuke
 mk libs
 mk install
-cd nxm/k10
-mk nuke
+mk kernels
 mk
-echo "Mission Success"
-exit 0
+
+# Boot the kernel and see if the output we get makes sense
+set +e
+qemu-system-x86_64 --kernel ~/nxm/sys/src/nxm/k10/9k8regression.elf  \
+	--nographic </dev/null > qemuout &
+set -e
+qemuproc=$!
+sleep 60
+kill -9 $!
+# things are not always identical. We need to do some filtering.
+# For now, just filter on the regression tests themselves.
+sed '1,/Morning/d' qemuout | diff - correctoutput
+date
+
